### ISSUE TITLE
Add advanced matching options to HTTP handler

### ISSUE THREAD

**Issue by prskr** [baez90/inetmock#7]
Instead of only matching on the request path a more advanced matching could be implemented like Skipper or Traefik are doing it for routing e.g.:

```yaml
x-response-rules: &httpResponseRules
  rules:
    - matcher: Path
      pattern: ".*\\.(?i)exe"
      response: /var/lib/inetmock/fakeFiles/sample.exe
    - matcher: Header
      header: Accept
      pattern: "application/octet-stream"
      response: /var/lib/inetmock/fakeFiles/sample.exe
```

A custom unmarshaler for the rules would be required but that's fairly easy to implement and it would improve the HTTP handling a lot
