### ISSUE TITLE
Allow overriding the handler for an HTTP request

### ISSUE THREAD

**Issue by prskr** [baez90/inetmock#8]
To make the request handling more flexible in the `http_handler` an optional `strategy` for a rule could be added:

```yaml
endpoints:
  plainHttp:
    handler: http_mock
    listenAddress: 0.0.0.0
    ports:
    - 80
    - 8000
    - 8080
    options:
      defaultStrategy: mock
      rules:
      - pattern: ".*\\.microsoft\\.com.*"
        response: ''
        strategy: passthrough
      - pattern: ".*"
        response: /var/lib/inetmock/fakeFiles/default.html
```
